services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload
    ports:
      - "8100:8100"
    depends_on:
      - postgres_db
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=postgres_db
      - DB_PORT=5432
      - DB_NAME=postgres
    volumes:
      - .:/app
    env_file: .env

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
